#***********************************************************
# Kurso "Informatika" 2009/2010 m.m. pavasario (2) sem.
# 2-as praktinis darbas. Uzduoties Nr. 219
# Darba atliko: Maksim Isajev
#***********************************************************


program : program.pas txt.ppw
	fpc program.pas

txt.ppw : txt.pas
	fpc txt.pas
