#***********************************************************
# Kurso "Informatika" 2009/2010 m.m. pavasario (2) sem.
# 1-as praktinis darbas. Uzduoties Nr. 119
# Darba atliko: Maksim Isajev
#***********************************************************
mais8353.exe : mais8353.pas
	fpc mais8353.pas