#***********************************************************
# Kurso "Informatika" 2009/2010 m.m. pavasario (2) sem.
# 3-as praktinis darbas. Uzduoties Nr. 319
# Darba atliko: Maksim Isajev
#***********************************************************


program : program.pas txtunit.ppw
	fpc program.pas

txtunit.ppw : txtUnit.pas
	fpc txtUnit.pas
